version: '3.8'

services:
  # Development service for interactive work
  dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: cpal-evictions-dev
    volumes:
      # Mount scripts directory for live code updates
      - ../scripts:/app/scripts
      # Mount data directory for persistent data
      - ../data:/app/data
      # Mount data directory for R script access (config expects /data)
      - ../data:/data
      # Mount SFTP data for live access
      - ../data/sftp-mount:/data/sftp-mount
      # Mount config for easy configuration changes
      - ../config.yml:/app/config.yml
      # Mount renv files for package management
      - ../renv.lock:/app/renv.lock
      - ../renv:/app/renv
      # Mount DESCRIPTION file
      - ../DESCRIPTION:/app/DESCRIPTION
      # Mount Google service account credentials
      - ../.gsuite-service.json:/var/run/secrets/google
      # Mount DCAD sync directory
      - ../data/dcad-sync:/dcad-sync
    environment:
      - ENV=development
      - R_CONFIG_FILE=/app/config.yml
      - GOOGLE_APPLICATION_CREDENTIALS=/var/run/secrets/google
      - TZ=America/Chicago
    working_dir: /app
    # Keep container running for interactive use
    entrypoint: ["bash", "-c", "while true; do sleep 30; done"]
    # Enable file watching for development
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .git/
            - renv/library/
            - data/
            - "*.log"
        - action: rebuild
          path: docker/Dockerfile.dev
        - action: rebuild
          path: renv.lock

  # Service for running specific R scripts
  analysis:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: cpal-evictions-analysis
    volumes:
      - ../scripts:/app/scripts
      - ../config.yml:/app/config.yml
      - ../renv.lock:/app/renv.lock
      - ../renv:/app/renv
      - ../DESCRIPTION:/app/DESCRIPTION
      # Mount Google service account credentials
      - ../.gsuite-service.json:/var/run/secrets/google
      # Mount data from sftp-sync container
      - sftp-data:/data
    environment:
      - ENV=development
      - R_CONFIG_FILE=/app/config.yml
      - GOOGLE_APPLICATION_CREDENTIALS=/var/run/secrets/google
      - TZ=America/Chicago
    working_dir: /app
    # Default command shows available scripts
    command: ["./entrypoint.sh"]
    depends_on:
      - data-sync
    profiles:
      - analysis

  # Combined service to download SFTP data and sync DCAD data
  data-sync:
    image: alpine:3.21
    container_name: cpal-evictions-data-sync
    volumes:
      - ./credentials/sftp/evictionsuser:/root/.ssh/evictionsuser:ro
      - sftp-data:/data
      - ../config.yml:/tmp/config.yml
    command: ["sh", "-c", "echo '=== Starting Data Sync Process ===' && echo 'Installing required packages...' && apk add --no-cache openssh-client rclone && echo 'Setting up SSH credentials...' && cp /root/.ssh/evictionsuser /tmp/evictionsuser && chmod 600 /tmp/evictionsuser && echo 'Cleaning up existing data...' && rm -rf /data/Dallas* /data/bubble /data/demo /data/filing* /data/geographies /data/dcad-sync /data/sftp-mount && echo 'Creating data subdirectories...' && mkdir -p /data/Dallas\\ County\\ Eviction\\ Master && mkdir -p /data/Dallas\\ County\\ Daily\\ Eviction\\ Reports/archive && mkdir -p /data/Dallas\\ County\\ Weekly\\ Eviction\\ Reports/archive && mkdir -p /data/bubble && mkdir -p /data/demo && mkdir -p /data/filing\\ data && mkdir -p /data/geographies && mkdir -p /data/dcad-sync && echo '=== Step 1: Downloading SFTP data... ===' && echo 'Downloading evictions data...' && echo 'get -r evictions/* /data/' | sftp -i /tmp/evictionsuser -o StrictHostKeyChecking=no data_team@s-99f83b3610f94e44a.server.transfer.us-east-1.amazonaws.com && echo 'Downloading dcad-sync data...' && echo 'get -r dcad-sync/* /data/dcad-sync/' | sftp -i /tmp/evictionsuser -o StrictHostKeyChecking=no data_team@s-99f83b3610f94e44a.server.transfer.us-east-1.amazonaws.com && echo 'SFTP data downloaded successfully!' && echo '=== Step 2: Syncing DCAD data... ===' && echo 'Copying DCAD sync script...' && wget -q https://raw.githubusercontent.com/childpovertyactionlab/cpal-evictions/main/acquisition/src/sync-dcad-evictions.sh -O /tmp/sync-dcad-evictions.sh && chmod +x /tmp/sync-dcad-evictions.sh && echo 'Running DCAD sync...' && sh /tmp/sync-dcad-evictions.sh /tmp/config.yml && echo '=== Data Sync Complete! ===' && echo 'Data available at /data/' && echo 'Keeping container alive for data access...' && while true; do sleep 30; done"]
    profiles:
      - data

volumes:
  # Shared volume for SFTP data (no local storage)
  sftp-data:
    driver: local
  # Named volume for persistent data (optional)
  cpal-data:
    driver: local